# Generated by Django 5.0.1 on 2024-02-01 19:42

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_alter_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 1, 19, 42, 11, 145038, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
