# Generated by Django 5.0.1 on 2024-02-01 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_userprofile_created_at_userprofile_expired_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='expired_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
