# Generated by Django 5.0.1 on 2024-02-07 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0008_alter_emailhistory_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailHistory',
        ),
    ]
