# Generated by Django 5.0.1 on 2024-02-08 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0012_emailhistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailHistory',
        ),
    ]
